import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Basir',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'Arseniy',
      email: 'Arseniy@gmail.com',
      password: bcrypt.hashSync('1', 8),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Project - X Water-resistant Black Japanese Hooded Overcoat Jacket',
      category: 'Jackets',
      image: '/images/p1.jpg',
      price: 60.12,
      countInStock: 10,
      brand: 'Project-X',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality Jacket ',
    },
    {
      name: 'Project - X Windbreaker Techwear Hoodied Jacket',
      category: 'Jackets',
      image: '/images/p2.jpg',
      price: 80.44,
      countInStock: 20,
      brand: 'Project-X',
      rating: 4.0,
      numReviews: 10,
      description: 'High quality Windbreaker',
    },
    {
      name: 'Simple And Stylish Pocket Pants',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 51.21,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.8,
      numReviews: 17,
      description: 'Techwear Pants',
    },
    {
      name: 'Techwear Multi-pocket Outdoor Multi-pocket Slacks',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 78.34,
      countInStock: 15,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 14,
      description: 'Techwear Pants',
    },
    {
      name: 'Cool Fashion Print Zipper Hoodie',
      category: 'Hoodie',
      image: '/images/p5.jpg',
      price: 23.45,
      countInStock: 5,
      brand: 'Cool Fashion',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality Hoodie',
    },
    {
      name: 'Function Multi-pocket Small High Neck Thin Style Hoodie',
      category: 'Hoodie',
      image: '/images/p6.jpg',
      price: 29.30,
      countInStock: 12,
      brand: 'Cool Fashion',
      rating: 4.5,
      numReviews: 15,
      description: 'High quality Hoodie',
    },
  ],
};
export default data;
